apiVersion: v1
kind: Secret
metadata:
  name: {{ include "migration-app.fullname" . }}-mongodb-secret
  labels:
    {{- include "migration-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.mongodb.databases }}
  {{- $dbNameUpper := upper .name | replace "-" "_" }}
  DB_{{ $dbNameUpper }}_URL: "mongodb://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}?authSource={{ .database }}"
  {{- end }}
